## variable type

In [1]:
a = 1; print(type(a))

<class 'int'>


In [2]:
a=1;b=2
a
b

2

#### show only b

In [3]:
a=1.2;b=2
print(a,b)
print(a); print(b) 

1.2 2
1.2
2


In [4]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [5]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [6]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [7]:
a="123"; print(type(a))
b="I love 'you'"; print(b);
print(a[0])
print(a[-1])

<class 'str'>
I love 'you'
1
3


#### variable[index]
#### index starts 0

In [8]:
a=str(a)
print(type(a))

<class 'str'>


In [9]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [10]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [11]:
a[2][0]

3

In [12]:
print(a[2][0])

3


#### If type(a) is 'string', print(a) does not show ' or ".

In [13]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


In [14]:
a = [1,'2', [3, '4']];
a[1]=100; print(a)

[1, 100, [3, '4']]


In [15]:
b = (1,'2', [3, '4']);
b[1]=100; print(b) 

TypeError: 'tuple' object does not support item assignment

#### tuple,unlike list, cannot change a value.

In [16]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


#### dictionary -> {key:value}
#### dic[key] returns value

In [17]:
print(a[1])

KeyError: 1

#### dictionary is unordered. indexing of dictionary is impossible.

In [18]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [19]:
print(type(a[0]))

<class 'tuple'>


## numpy

In [21]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


#### active library 'numpy' as np to use a matrix.
#### array(a) -> error

In [22]:
c=array(a); print(c)

NameError: name 'array' is not defined

In [23]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


##### 요소와 요소끼리 곱해짐.

In [24]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


##### array and marix is diferrent types. 

In [25]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

#### matrix(the number of rows, the number of columns)
#### (m,k)*(k,n) -> (m,n) 
#### (m,k)*(k2,n), k!=k2 -> error 

In [26]:
c*c.T

matrix([[14, 19],
        [19, 73]])

#### c.T -> c is transposed

#### numpy is a essential library for matrix operation